name: spirotrack
description: A Flutter health monitoring application.

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter

  # Hive for local database storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image picker for profile photo
  image_picker: ^1.0.4
  video_player: ^2.5.0

  # Path provider for file storage
  path_provider: ^2.1.1

  # ✅ Bluetooth Low Energy package
  flutter_blue_plus: ^1.32.11


  # ✅ Permission handler for Bluetooth and Location
  permission_handler: ^12.0.1

  # ✅ Optional — nice loading indicators (can be used for test progress)
  flutter_spinkit: ^5.2.1

  # Cupertino icons for iOS-style icons (optional but common)
  cupertino_icons: ^1.0.8

  intl: ^0.18.0

  app_settings: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive generator for creating type adapters (if needed later)
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/popupvideo.mp4
